package j66.free.tdlist.model;

import j66.free.tdlist.tools.Constant;
import j66.free.tdlist.tools.FileManager;
import org.jetbrains.jps.model.serialization.facet.FacetManagerState;

import java.time.LocalDate;
import java.util.Date;

abstract public class TodoListManager {
    private static boolean saved;
    private static TodoList todoList;

    public static TodoList getTodoList(){
        if (todoList == null)
            todoList = getSampleTodoList();
        return todoList;
    }

    public static TodoList getTodoList(boolean aSample){
        todoList = getSampleTodoList();
        return todoList;
    }

    private static TodoList getSampleTodoList(){

        TodoList sampleTodoList = new TodoList("TodoList : "+LocalDate.now().toString(),"Sample, autogenerated");

        Project project = new Project("Math Book","How to main Mathematics");
        SubProject subProject = new SubProject("Text","End the writting");
        subProject.addTask(new Task("Correction","Wait for corrector return"));
        subProject.addTask(new Task("Display","Design book on InDesign CC"));

        project.addSubProject(subProject);
        project.addTask(new Task("Look for a printer","According to the quality price ratio"));

        sampleTodoList.addProject(project);
        sampleTodoList.addTask(new Task("Sample Task","Just to show you that a task can be orphan"));

        return sampleTodoList;
    }

    public static boolean persistTodoList(){
        System.out.println(todoList.getName().replace(":","_")+new Date().getTime());
        return FileManager.writeFile(todoList, Constant.TODOLIST_PATH,todoList.getName().replace(":","_")+"_"+new Date().getTime());
    }

}
